# Generated by Django 5.1.5 on 2025-02-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0004_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
