# Generated by Django 5.1.5 on 2025-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0005_publication_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_done',
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Assigned', 'Assigned'), ('Overdue', 'Overdue')], default='Assigned', max_length=10),
        ),
    ]
