# Generated by Django 5.1.5 on 2025-02-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0006_remove_publication_is_done_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Assigned', 'Assigned'), ('Overdue', 'Overdue')], default='Assigned', max_length=10),
        ),
    ]
